# Generated by Django 4.2.6 on 2023-10-21 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('image', models.ImageField(upload_to='about/', verbose_name='Images')),
                ('info', models.TimeField(verbose_name='About Us')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Name')),
                ('info', models.TextField(verbose_name='Information')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('image', models.URLField(verbose_name='URL field')),
                ('set_data', models.DateField()),
                ('effects', models.CharField(choices=[('g', 'good'), ('v', 'very good'), ('i', 'interesting')], max_length=15, verbose_name='Effects')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.shop')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
